# Basic
name:               "boggs aldanese"
domain:             "boggs.xyz"
protocol:           "http://"

# URL
baseurl:            ""
permalink:          /blog/:title

# Markdown
markdown:           kramdown

# Navigation
nav:
  # - name:           "about"
  #   href:           "/about"
  - name:           "blog"
    href:           "/blog"
  - name:           "projects"
    href:           "/projects"

ext_nav:
  - name:           "github"
    href:           "https://github.com/b-ggs"
  - name:           "twitter"
    href:           "https://twitter.com/b_ggs"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
